# -*- coding: utf-8 -*-
"""Assemble docs/DECISIONS_NEEDED.md — the consolidated human-decision register.

Pre-gathers Grammar §-evidence for every open class decision so a reviewer (and then
Zalizniak) only has to confirm, not hunt. Reads (never writes) the data sources:
  review_queue.json            19 kept class additions (Queue A)
  src/grammar_refs.json        per-root Whitney §-citations, tagged by class_chapter
  scratch/phase0/root_spine.json   warnemyr-authoritative class per homonym (+ uncertain)
  scratch/phase0/audit.md      the 23 Phase-0 GAP/SMEAR flags

Authority order: Grammar > Whitney Roots > DCS corpus > Zalizniak. Nothing here is applied;
every row is EVIDENCE + a PROPOSAL. The human decides. UTF-8, no BOM.
"""
import sys, os, re, json
sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def P(*a): return os.path.join(BASE, *a)

queue  = json.load(open(P('review_queue.json'), encoding='utf-8'))['kept_pending_review']
grefs  = json.load(open(P('src','grammar_refs.json'), encoding='utf-8'))
spine  = json.load(open(P('scratch','phase0','root_spine.json'), encoding='utf-8'))
by_no  = {r['whitney_no']: r for r in spine if 'whitney_no' in r}

URGENT = {'473','578','890'}   # [I,VI]-onto-empty: the collapse the revert predicate can't catch

def chapter_set(eid):
    """Whitney grammar chapters (gaṇas) under which this root is actually discussed."""
    out = {}
    for ref in grefs.get(eid, {}).get('grammar_refs', []):
        cc = ref.get('class_chapter')
        if cc:
            for part in str(cc).split('_'):
                out.setdefault(part, []).append((ref['label'], ref.get('type',''), ref.get('snippet','')[:160]))
    return out

def grammar_supports(eid, gana):
    chs = chapter_set(eid)
    return chs.get(gana, [])

def proposal(item):
    eid, added = item['id'], item['added']
    supported = {g: grammar_supports(eid, g) for g in added}
    n_sup = sum(1 for g in added if supported[g])
    iv_pair = set(added) == {'I','VI'} or (set(added) & {'I','VI'} and not item['whitney_roots_classes'])
    if n_sup == len(added) and added:
        verdict = 'LEAN KEEP — Grammar cites this root under the added chapter(s). Confirm sense w/ Zalizniak.'
    elif n_sup == 0 and iv_pair:
        verdict = 'LEAN REVERT — no Grammar chapter cites the added class; I/VI is the unaccented-corpus artifact.'
    elif n_sup == 0:
        verdict = 'NEEDS ZALIZNIAK — added class has no Grammar chapter; corpus-only signal.'
    else:
        verdict = 'MIXED — part Grammar-supported; review each added class below.'
    return supported, verdict

def fmt_supported(supported):
    rows = []
    for g, hits in supported.items():
        if hits:
            labs = ', '.join(sorted({h[0] for h in hits}))
            rows.append(f'    - **+{g}**: Grammar **{labs}** ✓  _“{hits[0][2].strip()}…”_')
        else:
            rows.append(f'    - **+{g}**: ✗ no Grammar chapter cites class {g} for this root.')
    return '\n'.join(rows)

def wn_evidence(item):
    no = int(re.sub(r'\D','', item['id']))
    r = by_no.get(no)
    if not r: return '_(no warnemyr record)_'
    bits = [f"warnemyr class **{'/'.join(r['class']) or '—'}**"]
    if r.get('class_uncertain'): bits.append(f"uncertain {'/'.join(r['class_uncertain'])}")
    if r.get('gloss_short'):     bits.append(f"“{r['gloss_short']}”")
    return ' · '.join(bits)

out = []
out.append('# DECISIONS NEEDED — Whitney-root class & PPP curation\n')
out.append('Open decisions that require a Sanskritist (then **Zalizniak** as tiebreaker). '
           'Authority order: **Grammar > Whitney Roots > DCS corpus > Zalizniak**. '
           'Everything below is **evidence + a proposal** — nothing is applied. '
           'Companion to [REVIEWER_GUIDE.md](../REVIEWER_GUIDE.md) (full per-item algorithm, EN/RU) '
           'and [review_queue.json](../review_queue.json).\n')
out.append('Generated by `scripts/build_decisions_doc.py` from the data sources — regenerable, do not hand-edit.\n')
out.append('---\n')

# ---- Section 0: the 3 urgent I/VI-onto-empty ----
out.append('## 0. ⚠️ Highest priority — I/VI added together onto an empty baseline\n')
out.append('Flagged by code review: these were added **[I, VI] together** where Whitney lists **no** class. '
           'The revert predicate only catches a *single*-class I↔VI delta, so these slipped through and sit '
           '**live in `app_data.json`** as unaccented-corpus-derived classes with (check below) no Whitney support. '
           'The corpus *cannot* distinguish I from VI. Decide explicitly before treating as authoritative.\n')
for item in [q for q in queue if q['id'] in URGENT]:
    supported, verdict = proposal(item)
    out.append(f"### [{item['id']}] {item['root']} — added {item['added']}")
    out.append(f"- {wn_evidence(item)}")
    out.append(fmt_supported(supported))
    out.append(f"- **Proposal:** {verdict}\n")

# ---- Section 1: Queue A (the rest of the 19) ----
out.append('---\n')
out.append('## 1. Queue A — kept class additions (Grammar-§ checked)\n')
out.append('Each adds a *distinct* gaṇa on a corpus prompt. Grammar-chapter evidence pre-pulled from '
           '`src/grammar_refs.json`; confirm against the cited §, then Zalizniak.\n')
out.append('| # | root | Whitney | added | warnemyr | Grammar support for added | proposal |')
out.append('|--:|---|:-:|:-:|:-:|---|---|')
for item in [q for q in queue if q['id'] not in URGENT]:
    supported, verdict = proposal(item)
    sup = '; '.join(f"+{g}: {', '.join(sorted({h[0] for h in hits})) if hits else '✗'}"
                    for g, hits in supported.items())
    r = by_no.get(int(re.sub(r'\D','', item['id'])))
    wn = '/'.join(r['class']) if r and r['class'] else '—'
    tag = verdict.split(' — ')[0]
    out.append(f"| {item['id']} | {item['root']} | {'/'.join(item['whitney_roots_classes']) or '—'} "
               f"| {','.join(item['added'])} | {wn} | {sup} | {tag} |")
out.append('')

# ---- Section 2: Phase-0 GAP/SMEAR ----
out.append('---\n')
out.append('## 2. Phase-0 audit — warnemyr vs local class (23 flags)\n')
out.append('From `scratch/phase0/audit.md` (full warnemyr re-harvest of `1885/`). **GAP** = local `—` but '
           'warnemyr has a class (usually a safe capture-gap fix, e.g. kḷp → I). **SMEAR** = the classes '
           'disagree. ⚠️ **Caveat (DESIGN §6):** these are matched by *homonym number*, which is unreliable '
           'across sources — a SMEAR may be a homonym mis-alignment, not a real class change. Verify by '
           '*feature* (present-stem) before adopting warnemyr.\n')
gaps, smears = [], []
for line in open(P('scratch','phase0','audit.md'), encoding='utf-8'):
    m = re.match(r'\|\s*(\d+)\s*\|\s*(\S+)\s*\|\s*([1-9]?)\s*\|\s*(GAP|SMEAR)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|', line)
    if m:
        no, root, hom, typ, loc, wn = m.groups()
        (gaps if typ=='GAP' else smears).append((no, root, hom, loc, wn))
out.append(f'**GAP ({len(gaps)})** — local `—`, warnemyr supplies a class (lean adopt, verify not truly defective):\n')
out.append('| # | root | hom | warnemyr |')
out.append('|--:|---|:-:|:-:|')
for no, root, hom, loc, wn in gaps:
    out.append(f'| {no} | {root} | {hom} | {wn} |')
out.append(f'\n**SMEAR ({len(smears)})** — classes disagree; check homonym alignment + feature first:\n')
out.append('| # | root | hom | local | warnemyr |')
out.append('|--:|---|:-:|:-:|:-:|')
for no, root, hom, loc, wn in smears:
    out.append(f'| {no} | {root} | {hom} | {loc} | {wn} |')
out.append('')

# ---- Section 3: PPP + Section 4: unmatched ----
out.append('---\n')
out.append('## 3. PPP corrections — one open editorial call\n')
out.append('Queues B/C are largely applied (see [ppp_source_validation.md](../ppp_source_validation.md)). '
           'One item raised by code review: ids **349/350/351 (√dā)** now carry `ppp = [data, datta, dātta]` — '
           'the script added **`dātta`** while canonical **`datta`** was already present. `dātta` (long ā) is a '
           'non-standard PPP rendering. **Decide:** keep `dātta`, or collapse to canonical `datta`.\n')
out.append('---\n')
out.append('## 4. Alias-resolution debt — 9 warnemyr pages unmatched to Whitney numbering\n')
out.append('Vowel-length / bracketed-gloss cases from Phase 0 (see `crosswalk/_unmatched.csv`): '
           '`ṛj, mi, vā(in, dīv, dvar?, hru, hur, med[mid], modṣ`. Need a curated alias to bind each to its '
           'Whitney `whitney_no` (IAST↔SLP1 edge cases, DESIGN §10). Mechanical once the alias is chosen.\n')

with open(P('docs','DECISIONS_NEEDED.md'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(out))
print('wrote docs/DECISIONS_NEEDED.md  ·  queue items:', len(queue),
      '· urgent:', len(URGENT), '· gaps:', len(gaps), '· smears:', len(smears))
